/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Serg.Morgun (https://sketchfab.com/Serg.Morgun)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/drum-kit-99218427e7a2424ea8afc9b8c668a5c7
Title: Drum Kit
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    polySurface1365_phong4_0: THREE.Mesh;
    polySurface1378_phong4_0: THREE.Mesh;
    drums_lowpolySurface1269_phong5_0: THREE.Mesh;
    polySurface1386_phongE1_0: THREE.Mesh;
    polySurface1055_blinn2_0: THREE.Mesh;
    polySurface1323_group20_group19_group20_lambert1_0: THREE.Mesh;
    polySurface1387_lambert2_0: THREE.Mesh;
  };
  materials: {
    phong4: THREE.MeshStandardMaterial;
    phong5: THREE.MeshStandardMaterial;
    phongE1: THREE.MeshStandardMaterial;
    blinn2: THREE.MeshStandardMaterial;
    lambert1: THREE.MeshStandardMaterial;
    lambert2: THREE.MeshStandardMaterial;
  };
};

export default function Drum(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/drum_kit.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface1365_phong4_0.geometry}
          material={materials.phong4}
          position={[1.191, 2.346, -0.024]}
          rotation={[0, 0, 0.1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface1378_phong4_0.geometry}
          material={materials.phong4}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.drums_lowpolySurface1269_phong5_0.geometry}
        material={materials.phong5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface1386_phongE1_0.geometry}
        material={materials.phongE1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface1055_blinn2_0.geometry}
        material={materials.blinn2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.polySurface1323_group20_group19_group20_lambert1_0.geometry
        }
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface1387_lambert2_0.geometry}
        material={materials.lambert2}
      />
    </group>
  );
}

useGLTF.preload("/drum_kit.glb");
