/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['3']: THREE.Mesh;
    ['3outer']: THREE.Mesh;
    Object_39: THREE.Mesh;
    Object_39_1: THREE.Mesh;
    Object_39_2: THREE.Mesh;
    Object_39_3: THREE.Mesh;
    ['4']: THREE.Mesh;
    ['4outer']: THREE.Mesh;
    ['2']: THREE.Mesh;
    ['2outer']: THREE.Mesh;
    ['1outer']: THREE.Mesh;
    Object_65: THREE.Mesh;
    ['5']: THREE.Mesh;
    Object_107: THREE.Mesh;
  };
  materials: {
    White: THREE.MeshStandardMaterial;
    Black_Metal: THREE.MeshStandardMaterial;
    ['Metal.001']: THREE.MeshStandardMaterial;
    ['Black.001']: THREE.MeshStandardMaterial;
    Gold: THREE.MeshStandardMaterial;
  };
};

export default function Drum(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/drum-kit.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Bass(AndDrums)_39" position={[-2.208, 7.017, 19.077]} scale={8.819}>
        <group name="BassDrum_27" position={[0.004, 0.662, 0.207]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="3" castShadow receiveShadow geometry={nodes['3'].geometry} material={materials.White} />
          <mesh name="3outer" castShadow receiveShadow geometry={nodes['3outer'].geometry}>
            <meshStandardMaterial color="yellow" />
          </mesh>
          <mesh
            name="Object_39"
            castShadow
            receiveShadow
            geometry={nodes.Object_39.geometry}
            material={materials.Black_Metal}
          />
          <mesh
            name="Object_39_1"
            castShadow
            receiveShadow
            geometry={nodes.Object_39_1.geometry}
            material={materials['Metal.001']}
          />
          <mesh
            name="Object_39_2"
            castShadow
            receiveShadow
            geometry={nodes.Object_39_2.geometry}
            material={materials['Black.001']}
          />
          <mesh
            name="Object_39_3"
            castShadow
            receiveShadow
            geometry={nodes.Object_39_3.geometry}
            material={materials.Gold}
          />
        </group>
        <group
          name="Tom2Drum_36"
          position={[0.286, 1.313, 0.334]}
          rotation={[0.522, 0, 0]}
          scale={[0.588, 1.181, 0.588]}
        >
          <mesh name="4" castShadow receiveShadow geometry={nodes['4'].geometry} material={materials.White} />
          <mesh name="4outer" castShadow receiveShadow geometry={nodes['4outer'].geometry}>
            <meshStandardMaterial color="red" />
          </mesh>
        </group>
        <group
          name="Tom3Drum_37"
          position={[-0.291, 1.313, 0.337]}
          rotation={[0.522, 0, 0]}
          scale={[0.574, 1.151, 0.574]}
        >
          <mesh name="2" castShadow receiveShadow geometry={nodes['2'].geometry} material={materials.White} />
          <mesh name="2outer" castShadow receiveShadow geometry={nodes['2outer'].geometry}>
            <meshStandardMaterial color="blue" />
          </mesh>
        </group>
      </group>
      <group name="Snare_26" position={[-7.192, 7.562, 26.566]} scale={3.333}>
        <group name="1" position={[0.069, 2.84, -0.013]} rotation={[-0.028, -0.07, -0.219]} scale={2.243}>
          <mesh
            name="1outer"
            castShadow
            receiveShadow
            geometry={nodes['1outer'].geometry}
            material={nodes['1outer'].material}
          >
            <meshStandardMaterial color="orange" />
          </mesh>
          <mesh
            name="Object_65"
            castShadow
            receiveShadow
            geometry={nodes.Object_65.geometry}
            material={materials.White}
          />
        </group>
      </group>
      <group name="Tom_42" position={[5.298, 7.86, 25.988]} rotation={[Math.PI, -1.051, Math.PI]} scale={3.333}>
        <group name="Tom1Drum_40" position={[0.011, 1.798, 0.019]} rotation={[-Math.PI, 1.051, -Math.PI]} scale={2.646}>
          <mesh name="5" castShadow receiveShadow geometry={nodes['5'].geometry} material={materials.White} />
          <mesh name="5outer" castShadow receiveShadow geometry={nodes.Object_107.geometry}>
            <meshStandardMaterial color="green" />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/drum-kit.glb');
