/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: CamSear16 (https://sketchfab.com/CamSear16)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/guitar-hero-controller-bcac8f9f95a44008ad90f470326e5fca
Title: Guitar Hero Controller
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
  };
  materials: {
    Material__26: THREE.MeshStandardMaterial;
  };
};

export default function Guitar(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/guitar_hero_controller.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.003}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Material__26}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Material__26}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Material__26}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/guitar_hero_controller.glb");
