/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial003: THREE.Mesh;
    defaultMaterial112: THREE.Mesh;
  };
};

export default function Lanterns(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('./models/lanterns.glb') as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.defaultMaterial003.geometry}>
        <meshStandardMaterial emissive={"#F9CB43"} emissiveIntensity={1} color="#F9CB43" />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.defaultMaterial112.geometry}>
        <meshStandardMaterial emissive={"#F9CB43"} emissiveIntensity={1} color="#F9CB43" />
      </mesh>
    </group>
  );
}

useGLTF.preload('./models/lanterns.glb');
