/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: lena-wachs (https://sketchfab.com/lena-wachs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/black-sabbath-band-poster-3322b789f5b7412faf5e930fd1eafeb6
Title: Black Sabbath Band Poster
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useRef } from 'react';
import { useFrame } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    Poster1_poster_mat_0: THREE.Mesh;
  };
  materials: {
    poster_mat: THREE.MeshStandardMaterial;
  };
};

export default function Poster(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./models/poster.glb') as GLTFResult;
  const meshref = useRef<THREE.Mesh>(null);

  useFrame((state) => {
    if (meshref.current) {
      const time = state.clock.elapsedTime;
      const amplitude = 0.2;
      const offset = Math.sin(time) * amplitude;
      meshref.current.rotation.x = 2.6 + offset;
      meshref.current.rotation.z = -3.5 + offset / 2;
    }
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshref}
        geometry={nodes.Poster1_poster_mat_0.geometry}
        material={materials.poster_mat}
        position={[-12.026, 20.855, 0.934]}
        rotation={[2.855, 0.1, 2.68]}
        scale={0.066}
      />
    </group>
  );
}

useGLTF.preload('./models/poster.glb');
