/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF, useTexture } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    disk_inner2: THREE.Mesh;
    ['#REC0002_33_Highway_To_Hell_#REC0002_Textures_0']: THREE.Mesh;
    vinyl_face3: THREE.Mesh;
    vinyl_box_face002: THREE.Mesh;
    vinyl_face1: THREE.Mesh;
    vinyl_box_face003: THREE.Mesh;
    vinyl_face4: THREE.Mesh;
    vinyl_box_face004: THREE.Mesh;
    disk_inner1: THREE.Mesh;
    ['#REC0002_33_Highway_To_Hell_#REC0002_Textures_0001']: THREE.Mesh;
    vinyl_face2: THREE.Mesh;
    vinyl_box_face005: THREE.Mesh;
    vinyl_face5: THREE.Mesh;
    vinyl_box_face006: THREE.Mesh;
  };
  materials: {
    REC0002_Textures: THREE.MeshStandardMaterial;
    dit2: THREE.MeshStandardMaterial;
  };
};

export default function Vinyls(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/vinyls.glb') as GLTFResult;
  const judasPriest = useTexture('/assets/judas-priest.jpeg');
  const motorhead = useTexture('/assets/motorhead.jpeg');
  const megadeth = useTexture('/assets/megadeth.jpeg');

  megadeth.flipY = false;
  judasPriest.flipY = false;
  motorhead.flipY = false;

  return (
    <group {...props} dispose={null}>
      <mesh
        name="disk_inner2"
        castShadow
        receiveShadow
        geometry={nodes.disk_inner2.geometry}
        material={nodes.disk_inner2.material}
      />
      <mesh
        name="#REC0002_33_Highway_To_Hell_#REC0002_Textures_0"
        castShadow
        receiveShadow
        geometry={nodes['#REC0002_33_Highway_To_Hell_#REC0002_Textures_0'].geometry}
        material={materials.REC0002_Textures}
      />
      <mesh name="vinyl_face3" castShadow receiveShadow geometry={nodes.vinyl_face3.geometry}>
        <meshBasicMaterial map={judasPriest} />
      </mesh>
      <mesh
        name="vinyl_box_face002"
        castShadow
        receiveShadow
        geometry={nodes.vinyl_box_face002.geometry}
        material={materials.dit2}
      />
      <mesh name="vinyl_face1" castShadow receiveShadow geometry={nodes.vinyl_face1.geometry}>
        <meshBasicMaterial map={motorhead} />
      </mesh>
      <mesh
        name="vinyl_box_face003"
        castShadow
        receiveShadow
        geometry={nodes.vinyl_box_face003.geometry}
        material={materials.dit2}
      />
      <mesh name="vinyl_face4" castShadow receiveShadow geometry={nodes.vinyl_face4.geometry}>
        <meshBasicMaterial map={megadeth} />
      </mesh>
      <mesh
        name="vinyl_box_face004"
        castShadow
        receiveShadow
        geometry={nodes.vinyl_box_face004.geometry}
        material={materials.dit2}
      />
      <mesh
        name="disk_inner1"
        castShadow
        receiveShadow
        geometry={nodes.disk_inner1.geometry}
        material={nodes.disk_inner1.material}
      />
      <mesh
        name="#REC0002_33_Highway_To_Hell_#REC0002_Textures_0001"
        castShadow
        receiveShadow
        geometry={nodes['#REC0002_33_Highway_To_Hell_#REC0002_Textures_0001'].geometry}
        material={materials.REC0002_Textures}
      />
      <mesh
        name="vinyl_face2"
        castShadow
        receiveShadow
        geometry={nodes.vinyl_face2.geometry}
        material={nodes.vinyl_face2.material}
      />
      <mesh
        name="vinyl_box_face005"
        castShadow
        receiveShadow
        geometry={nodes.vinyl_box_face005.geometry}
        material={materials.dit2}
      />
      <mesh
        name="vinyl_face5"
        castShadow
        receiveShadow
        geometry={nodes.vinyl_face5.geometry}
        material={nodes.vinyl_face5.material}
      />
      <mesh
        name="vinyl_box_face006"
        castShadow
        receiveShadow
        geometry={nodes.vinyl_box_face006.geometry}
        material={materials.dit2}
      />
    </group>
  );
}

useGLTF.preload('/models/vinyls.glb');
